config/routes.rb
Rails.application.routes.draw do
  mount Spina::Engine => '/blog'
  resources :projects
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'
  get '/portfolio', to: 'projects#index', as: '/portfolio'
  get '/blog', to: 'posts#index', as: '/blog'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  has_rich_text :content
end

app/models/project.rb
class Project < ApplicationRecord
  has_rich_text :content
  has_one_attached :image

  def self.personal
    where(category: 'personal')
  end

  def self.professional
    where(category: 'professional')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index; end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    professional_projects = Project.professional
    personal_projects = Project.personal
    @projects = {professional: professional_projects, personal: personal_projects}
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/default/pages/homepage.html.erb
<h1><%= current_page.title %></h1>
<%= content.html :text %>

app/views/default/pages/show.html.erb
<h1><%= current_page.title %></h1>
<%= content.html(:text) %>

app/views/default/shared/_navigation.html.erb
<% presenter = Spina::MenuPresenter.new(Spina::Page.all) %>
<%= presenter.to_html %>

app/views/home/index.html.erb
<div class="ui text container">
  <h1 class="ui header inverted">Hello, this is Anna Costalonga</h1>
  <div class="sub header">I am a software engineer and a writer</div>
</div>
</div>
<div class="ui vertical stripe segment">
  <div class="ui middle aligned stackable grid container">
    <div class="row">
      <div class="eight wide column">
        <h3 class="ui centered header">About Me</h3>
        <p>We can give your company superpowers to do things that they never thought possible. Let us delight your customers and empower your needs...through pure data analytics.</p>
        <p>Yes that is right, you thought it was the stuff of dreams, but even bananas can be bioengineered.</p>
      </div>
      <div class="six wide right floated column">
        <%= image_tag 'anna_lila.jpg', class: "ui medium bordered image" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnnacostalongaPortfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="pushable cz-move-body-down">
    <div class="pusher">
      <div class="ui inverted vertical masthead center aligned segment">
        <%= render 'shared/nav' %>
        <%= yield %>
        <%= render 'shared/nav_footer' %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/default/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= current_spina_account.name %></title>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'default/shared/navigation' %>
    
    <%= yield %>
  </body>
</html>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

app/views/projects/index.html.erb
<h1 class="ui header">My Projects</h1>

<div class="ui container" id="projects">
  <div class="ui stackable three column grid">
    <% @projects.each do |category, projects| %>
      <h3><%= category.to_s.capitalize %> Projects</h3>
      <div class="row">

          <%= render(ProjectComponent.with_collection(projects)) %>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<h1>Projects#new</h1>
<p>Find me in app/views/projects/new.html.erb</p>

app/views/shared/_nav.html.erb
<div class="ui container">
  <div class="ui large secondary inverted pointing menu" id="nav_desktop">
    <%= link_to 'Home', root_path, class: "item" %>
    <%= link_to 'Portfolio', portfolio_path, class: "item" %>
    <%= link_to 'Blog', blog_path, class: "item" %>
    <div class="right item">
      <a class="ui inverted button">Contact me</a>
    </div>
  </div>
</div>

app/views/shared/_nav_footer.html.erb
<div class="ui container" id="footer_nav">
  <div class="ui large secondary inverted menu" id="footer_nav_items" >
    <%= link_to 'Home', root_path, class: "item"%>
    <%= link_to 'Portfolio', portfolio_path, class: "item" %>
    <%= link_to 'Blog', blog_path, class: "item" %>
    <%= link_to 'Contact me', '#', class: "item" %>
    </div>
  </div>
</div>